api_login_check:
    path: /api/login_check

api:
    resource: '.'
    type: 'api_platform'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Action/'
    type: 'annotation'
